version: "3"

services:
  pyramidapp:
    image: pyramidapp:latest
    build: 
      context: ./config
    working_dir: /var/app
    env_file: ./config/.env
    container_name: pyramidapp
    networks:
      - app_net
    volumes:
      - ./app:/var/app/
    command: ["python", "app.py"]
    ports:
     - "80:5000" #this port is open for testing purposes only
networks:
  app_net:

